name: nt
favicon: null
layout_spectrum: 0.6652662898413837
typography_spectrum: 0.2917627652641386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2975497709121555
  lightness: 0.14648085343651474
  saturation: 0.5131237753666937
  rhythmicContrast: 0.32935229293070734
purpose: []
